
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/Keye/modular_Keye.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_Keye.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen Team and The HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from typing import List, Union

from transformers.feature_extraction_utils import BatchFeature
from transformers.image_utils import ImageInput, VideoInput
from transformers.processing_utils import ProcessingKwargs, ProcessorMixin, Unpack, VideosKwargs
from transformers.tokenization_utils_base import PreTokenizedInput, TextInput
from .image_processing_keye import SiglipImageProcessor
import torch
from itertools import chain
import math


class KeyeVideosProcessorKwargs(VideosKwargs, total=False):
    fps: Union[List[float], float]


class KeyeProcessorKwargs(ProcessingKwargs, total=False):
    videos_kwargs: KeyeVideosProcessorKwargs
    _defaults = {
        "text_kwargs": {
            "padding": False,
        },
        "videos_kwargs": {"fps": 2.0},
    }

def split_thw(tensor):
    """Split grid_thw in t dimension, the result tensor should like [[1, h, w],...]"""
    repeats = tensor[:, 0]
    new_thw = torch.cat([
        torch.ones(tensor.shape[0], 1, dtype=tensor.dtype,
            device=tensor.device),
        tensor[:, 1:]
    ], dim=1)
    return torch.repeat_interleave(new_thw, repeats, dim=0)

def merge_hws(hws):
    """
    优化版本：使用更高效的方法合并张量
    """
    merged = []
    last_hw = [-1, -1]
    
    for hw in hws:
        # 找到连续相同形状的张量
        if hw[1:] == last_hw:
            merged[-1][0] += 1
        else:
            merged.append(hw)
            last_hw = hw[1:]
    
    return torch.tensor(merged)




class KeyeProcessor(ProcessorMixin):
    r"""
    [`KeyeProcessor`] offers all the functionalities of [`SiglipImageProcessor`] and [`Qwen2TokenizerFast`]. See the
    [`~KeyeProcessor.__call__`] and [`~KeyeProcessor.decode`] for more information.
    Args:
        image_processor ([`SiglipImageProcessor`], *optional*):
            The image processor is a required input.
        tokenizer ([`Qwen2TokenizerFast`], *optional*):
            The tokenizer is a required input.
        chat_template (`str`, *optional*): A Jinja template which will be used to convert lists of messages
            in a chat into a tokenizable string.
    """

    attributes = ["image_processor", "tokenizer"]
    valid_kwargs = ["chat_template","image_std", "min_pixels", "image_mean", "merge_size", "image_processor_type", "temporal_patch_size", "patch_size", "max_pixels"]

    image_processor_class = "AutoImageProcessor"
    tokenizer_class = ("Qwen2Tokenizer", "Qwen2TokenizerFast")

    def __init__(self, image_processor=None, tokenizer=None, chat_template=None, **kwargs):
        self.image_token = "<|image_pad|>" if not hasattr(tokenizer, "image_token") else tokenizer.image_token
        self.video_token = "<|video_pad|>" if not hasattr(tokenizer, "video_token") else tokenizer.video_token
        self.frame_token = "<|frame|>" if not hasattr(tokenizer, "frame_token") else tokenizer.frame_token
        self.fast_video_token = "<|fast_video_pad|>" if not hasattr(tokenizer, "fast_video_token") else tokenizer.fast_video_token
        self.fast_start = "<|fast_start|>" if not hasattr(tokenizer, "fast_start") else tokenizer.fast_start
        self.fast_end = "<|fast_end|>" if not hasattr(tokenizer, "fast_end") else tokenizer.fast_end
        super().__init__(image_processor, tokenizer, chat_template=chat_template)

        # self.fast_patch_size = 16
        # self.fast_image_processor = SiglipImageProcessor(patch_size=self.fast_patch_size)
        self.slowfast = True

    def __call__(
        self,
        images: ImageInput = None,
        text: Union[TextInput, PreTokenizedInput, List[TextInput], List[PreTokenizedInput]] = None,
        videos: VideoInput = None,
        **kwargs: Unpack[KeyeProcessorKwargs],
    ) -> BatchFeature:
        """
        Main method to prepare for the model one or several sequences(s) and image(s). This method forwards the `text`
        and `kwargs` arguments to Qwen2TokenizerFast's [`~Qwen2TokenizerFast.__call__`] if `text` is not `None` to encode
        the text. To prepare the vision inputs, this method forwards the `vision_infos` and `kwrags` arguments to
        SiglipImageProcessor's [`~SiglipImageProcessor.__call__`] if `vision_infos` is not `None`.

        Args:
            images (`PIL.Image.Image`, `np.ndarray`, `torch.Tensor`, `List[PIL.Image.Image]`, `List[np.ndarray]`, `List[torch.Tensor]`):
                The image or batch of images to be prepared. Each image can be a PIL image, NumPy array or PyTorch
                tensor. Both channels-first and channels-last formats are supported.
            text (`str`, `List[str]`, `List[List[str]]`):
                The sequence or batch of sequences to be encoded. Each sequence can be a string or a list of strings
                (pretokenized string). If the sequences are provided as list of strings (pretokenized), you must set
                `is_split_into_words=True` (to lift the ambiguity with a batch of sequences).
            videos (`np.ndarray`, `torch.Tensor`, `List[np.ndarray]`, `List[torch.Tensor]`):
                The image or batch of videos to be prepared. Each video can be a 4D NumPy array or PyTorch
                tensor, or a nested list of 3D frames. Both channels-first and channels-last formats are supported.
            return_tensors (`str` or [`~utils.TensorType`], *optional*):
                If set, will return tensors of a particular framework. Acceptable values are:
                - `'tf'`: Return TensorFlow `tf.constant` objects.
                - `'pt'`: Return PyTorch `torch.Tensor` objects.
                - `'np'`: Return NumPy `np.ndarray` objects.
                - `'jax'`: Return JAX `jnp.ndarray` objects.

        Returns:
            [`BatchFeature`]: A [`BatchFeature`] with the following fields:

            - **input_ids** -- List of token ids to be fed to a model. Returned when `text` is not `None`.
            - **attention_mask** -- List of indices specifying which tokens should be attended to by the model (when
              `return_attention_mask=True` or if *"attention_mask"* is in `self.model_input_names` and if `text` is not
              `None`).
            - **pixel_values** -- Pixel values to be fed to a model. Returned when `images` is not `None`.
            - **pixel_values_videos** -- Pixel values of videos to be fed to a model. Returned when `videos` is not `None`.
            - **image_grid_thw** -- List of image 3D grid in LLM. Returned when `images` is not `None`.
            - **video_grid_thw** -- List of video 3D grid in LLM. Returned when `videos` is not `None`.
            - **second_per_grid_ts** -- List of video seconds per time grid. Returned when `videos` is not `None`.
        """
        output_kwargs = self._merge_kwargs(
            KeyeProcessorKwargs,
            tokenizer_init_kwargs=self.tokenizer.init_kwargs,
            **kwargs,
        )
        if images is not None:
            slow_images = images
            image_inputs = self.image_processor(images=slow_images, return_tensors="pt")
            image_inputs['pixel_values'] = image_inputs['pixel_values']
            image_grid_thw = image_inputs["image_grid_thw"]
        else:
            image_inputs = {}
            image_grid_thw = None

        num_frames=[]
        if videos is not None:
            #TODO: add video processing
            all_slow_videos = []
            all_fast_videos = []
            # 这个是因为视频会划分为多张图片，需要在这个地方提前统计好token量，后面就不清楚界限在哪了
            all_position = []
            for current_index, current_video in enumerate(videos):
                if len(current_video) == 4: # slow_frames, fast_frames, time_position, slow_fast_order, 这里需要注意的是fast_frames，有可能和slow的长度不等，需要靠slow_fast_order来进行识别
                    slow_frames, fast_frames, time_position, slow_fast_order = current_video[0], current_video[1], current_video[2], current_video[3]
                    num_frames.append(len(slow_fast_order))
                    all_position.append((time_position, slow_fast_order))
                    ####### slow part #########
                    if slow_frames is not None:
                        slow_videos_inputs = self.image_processor(images=None, videos=slow_frames, **output_kwargs["images_kwargs"])
                        slow_video_grid_thw = slow_videos_inputs["video_grid_thw"]
                        # print("maosiyang::slow_video_grid_thw",slow_video_grid_thw,slow_fast_order)
                        all_slow_videos.append(slow_videos_inputs)
                        #slow_videos_token_nums[current_index] = slow_video_grid_thw.prod(dim=1).tolist() # 当前这个视频的所有token数
                    else:
                        all_slow_videos.append(None) # 这样的话，slow_fast_order都是1了，这里应该不会用到的
                        #slow_videos_token_nums[current_index] = None # 如果全为fast？但目前不存在这种情况
                    ###########################

                    ####### fast part #########
                    if self.slowfast:
                        if fast_frames is not None:
                            fast_videos_inputs = self.image_processor(images=None, videos=fast_frames, **output_kwargs["images_kwargs"])
                            fast_video_grid_thw = fast_videos_inputs["video_grid_thw"]
                            all_fast_videos.append(fast_videos_inputs)
                        else:
                            all_fast_videos.append(None) # 如果全为slow
                    ###########################
                else:
                    slow_frames, fast_frames, slow_fast_order = current_video[0], current_video[1], current_video[2]
                    num_frames.append(len(slow_fast_order))
                    image_video_pad = kwargs.get("image_video_pad", False)
                    if image_video_pad:
                        fast_frames = slow_frames
                        slow_fast_order += [1]

                    all_position.append((None, slow_fast_order))
                    ####### slow part #########
                    if slow_frames is not None:
                        if image_video_pad:
                            slow_videos_inputs = self.image_processor.preprocess(
                                images=None,
                                videos=slow_frames,
                                size={"height": 28, "width": 28},
                                **output_kwargs["images_kwargs"],
                            )
                        else:
                            slow_videos_inputs = self.image_processor(
                                images=None,
                                videos=slow_frames,
                                **output_kwargs["images_kwargs"],
                            )
                        slow_video_grid_thw = slow_videos_inputs["video_grid_thw"]
                        print("maosiyang2222222222::slow_video_grid_thw", slow_video_grid_thw, slow_fast_order)
                        all_slow_videos.append(slow_videos_inputs)
                    else:
                        all_slow_videos.append(None) # 这样的话，slow_fast_order都是1了，这里应该不会用到的
                    ####### fast part #########
                    if self.slowfast:
                        if fast_frames is not None:
                            if image_video_pad:
                                fast_videos_inputs = self.image_processor.preprocess(
                                    images=None,
                                    videos=fast_frames,
                                    size={"height": 28, "width": 28},
                                    **output_kwargs["images_kwargs"],
                                )
                            else:
                                fast_videos_inputs = self.image_processor(
                                    images=None,
                                    videos=fast_frames,
                                    **output_kwargs["images_kwargs"],
                                )
                            fast_video_grid_thw = fast_videos_inputs["video_grid_thw"]

                            all_fast_videos.append(fast_videos_inputs)
                        else:
                            all_fast_videos.append(None)
                    ###########################


            # todo: zdj debug 多次concat速度会慢很多
            slow_pixel_values_videos_list = [single_slow_video["pixel_values_videos"] for single_slow_video in all_slow_videos if single_slow_video is not None]
            slow_video_grid_thw_list = [single_slow_video["video_grid_thw"] for single_slow_video in all_slow_videos if single_slow_video is not None]

            total_slow_pixel_values_videos = torch.concat(slow_pixel_values_videos_list, dim=0)
            total_slow_video_grid_thw = torch.concat(slow_video_grid_thw_list, dim=0)
            # todo: zdj debug end
            # if len(total_slow_pixel_values_videos):
            #     videos_inputs = {
            #         "pixel_values_videos": total_slow_pixel_values_videos,
            #         "video_grid_thw": total_slow_video_grid_thw,
            #     }
            #     video_grid_thw = videos_inputs["video_grid_thw"]
            # else:
            #     videos_inputs = {}
            #     video_grid_thw = None

            if self.slowfast:
                # todo: zdj debug 多次concat速度会慢很多
                fast_pixel_values_videos_list = [single_fast_video["pixel_values_videos"] for single_fast_video in all_fast_videos if single_fast_video is not None]
                fast_video_grid_thw_list = [single_fast_video["video_grid_thw"] for single_fast_video in all_fast_videos if single_fast_video is not None]

                if len(fast_pixel_values_videos_list):
                    print('maosiyang::::fast_pixel_values_videos_list',[x.shape for x in fast_pixel_values_videos_list])
                    videos_inputs["fast_pixel_values_videos"] = torch.concat(fast_pixel_values_videos_list, dim=0)
                    videos_inputs["fast_video_grid_thw"] = torch.concat(fast_video_grid_thw_list, dim=0)
                    fast_video_grid_thw = videos_inputs["fast_video_grid_thw"]
                else:
                    fast_video_grid_thw = None

                # todo: zdj debug end
        else:
            videos_inputs = {}
            video_grid_thw = None
            fast_video_grid_thw = None
            slow_video_grid_thw = None


        if not isinstance(text, list):
            text = [text]

        if image_grid_thw is not None:
            index = 0
            for i in range(len(text)):
                while self.image_token in text[i]:
                    image_place_holder_tempale = "<|placeholder|>" * (image_grid_thw[index].prod()//self.image_processor.merge_size//self.image_processor.merge_size)
                    text[i] = text[i].replace(
                        self.image_token,
                        image_place_holder_tempale,
                        1,
                    )
                    index += 1
                text[i] = text[i].replace("<|placeholder|>", self.image_token)
        pixel_values_videos = []
        video_grid_thw = []
        videos_inputs = {}
            # text[0].count("<|placeholder|>")
        #if video_grid_thw is not None or fast_video_grid_thw is not None:
        if slow_video_grid_thw is not None:
            slow_video_grid_thw = split_thw(slow_video_grid_thw)
            if fast_video_grid_thw is not None:
                fast_video_grid_thw = split_thw(fast_video_grid_thw)

            def group_frame_indices_by_second(time_positions, num_frames):
                """
                将同一秒内的帧索引聚合；若缺少时间戳则逐帧成组。
                """
                if (
                    time_positions is None
                    or not isinstance(time_positions, (list, tuple))
                    or len(time_positions) < num_frames
                ):
                    return [[idx] for idx in range(num_frames)]

                groups = []
                current_group = []
                current_second = None
                for frame_idx, ts in enumerate(time_positions[:num_frames]):
                    sec = math.floor(ts)
                    if current_group and sec != current_second:
                        groups.append(current_group)
                        current_group = []
                    current_group.append(frame_idx)
                    current_second = sec

                if current_group:
                    groups.append(current_group)

                if not groups:
                    groups = [[idx] for idx in range(num_frames)]

                return groups

            frame_groups_per_video = []
            for time_position, slow_fast_order in all_position:
                groups = group_frame_indices_by_second(time_position, len(slow_fast_order))
                frame_groups_per_video.append(groups)

            index = 0
            slow_index = 0
            fast_index = 0
            slow_pixels_index = 0
            fast_pixels_index = 0
            for i in range(len(text)):
                while self.video_token in text[i]:
                    time_position, slow_fast_order = all_position[index]
                    video_place_holder_tempale = ""
                    expected_placeholders = 0
                    frame_groups = frame_groups_per_video[index]
                    if not frame_groups:
                        frame_groups = [[frame_idx] for frame_idx in range(len(slow_fast_order))]

                    for group in frame_groups:
                        group_timestamp = None
                        if time_position is not None and len(time_position) > group[0]:
                            group_timestamp = time_position[group[0]]

                        if group_timestamp is not None:
                            video_place_holder_tempale += self.frame_token + format(group_timestamp, ".1f")
                        else:
                            video_place_holder_tempale += self.frame_token

                        representative_num_patches = None
                        group_type = slow_fast_order[group[0]]
                        group_grid = None

                        for _ in group:
                            if group_type == 0:
                                # print("maosiyang::slow_video_grid_thw",slow_video_grid_thw,slow_fast_order)
                                current_grid = slow_video_grid_thw[slow_index]
                                num_patches = int(current_grid.prod())
                                pixel_values_videos.append(
                                    total_slow_pixel_values_videos[
                                        slow_pixels_index:slow_pixels_index + num_patches
                                    ]
                                )
                                slow_pixels_index += num_patches
                                slow_index += 1
                            else:
                                raise ValueError("Encountered fast frame but fast_video_grid_thw is None.")
                                current_grid = fast_video_grid_thw[fast_index]
                                num_patches = int(current_grid.prod())
                                pixel_values_videos.append(
                                    total_fast_pixel_values_videos[
                                        fast_pixels_index:fast_pixels_index + num_patches
                                    ]
                                )
                                fast_pixels_index += num_patches
                                fast_index += 1

                            if group_grid is None:
                                group_grid = current_grid.clone()

                            if representative_num_patches is None:
                                representative_num_patches = num_patches
                            elif representative_num_patches != num_patches:
                                raise ValueError(
                                    f"Grouped frames have inconsistent patch counts: video_idx={index}, group={group}"
                                )

                        if representative_num_patches is None or group_grid is None:
                            raise ValueError(f"Empty frame group detected for video {index}: {group}")

                        group_grid = group_grid.clone()
                        group_grid[0] = len(group)
                        video_grid_thw.append(group_grid)

                        placeholder_repeat = (
                            representative_num_patches
                            // self.image_processor.merge_size
                            // self.image_processor.merge_size
                        )
                        expected_placeholders += placeholder_repeat
                        video_place_holder_tempale += "<|placeholder|>" * placeholder_repeat

                    actual_placeholders = video_place_holder_tempale.count("<|placeholder|>")
                    if actual_placeholders != expected_placeholders:
                        raise ValueError(
                            f"Video placeholder mismatch: expected={expected_placeholders}, actual={actual_placeholders}, "
                            f"group_num={len(frame_groups)}, index={index}"
                        )
                    text[i] = text[i].replace(
                        self.video_token,
                        video_place_holder_tempale,
                        1,
                    )
                    index += 1
                text[i] = text[i].replace("<|placeholder|>", self.video_token)
                text[i] = text[i].replace("<|fast_placeholder|>", self.fast_video_token)
            # text[0].count(self.video_token)
            videos_inputs["pixel_values_videos"] = torch.cat(pixel_values_videos, dim=0)
            videos_inputs["video_grid_thw"] = torch.stack(video_grid_thw, dim=0)
            videos_inputs["num_frames"] = torch.tensor(num_frames)
        else:
            videos_inputs = {}
            video_grid_thw = None
            fast_video_grid_thw = None
            videos_inputs["num_frames"] = torch.tensor(num_frames)
        text_inputs = self.tokenizer(text, **output_kwargs["text_kwargs"])
        # print("processor:video_input", videos_inputs['video_grid_thw'])
        # print("pixel_values_videos:",videos_inputs['pixel_values_videos'].shape)
        # print("num_frames:",videos_inputs['num_frames'])
        return BatchFeature(data={**text_inputs, **image_inputs, **videos_inputs})

    def batch_decode(self, *args, **kwargs):
        """
        This method forwards all its arguments to Qwen2TokenizerFast's [`~PreTrainedTokenizer.batch_decode`]. Please
        refer to the docstring of this method for more information.
        """
        return self.tokenizer.batch_decode(*args, **kwargs)

    def decode(self, *args, **kwargs):
        """
        This method forwards all its arguments to Qwen2TokenizerFast's [`~PreTrainedTokenizer.decode`]. Please refer to
        the docstring of this method for more information.
        """
        return self.tokenizer.decode(*args, **kwargs)

    def post_process_image_text_to_text(
        self, generated_outputs, skip_special_tokens=True, clean_up_tokenization_spaces=False, **kwargs
    ):
        """
        Post-process the output of the model to decode the text.

        Args:
            generated_outputs (`torch.Tensor` or `np.ndarray`):
                The output of the model `generate` function. The output is expected to be a tensor of shape `(batch_size, sequence_length)`
                or `(sequence_length,)`.
            skip_special_tokens (`bool`, *optional*, defaults to `True`):
                Whether or not to remove special tokens in the output. Argument passed to the tokenizer's `batch_decode` method.
            Clean_up_tokenization_spaces (`bool`, *optional*, defaults to `False`):
                Whether or not to clean up the tokenization spaces. Argument passed to the tokenizer's `batch_decode` method.
            **kwargs:
                Additional arguments to be passed to the tokenizer's `batch_decode method`.

        Returns:
            `List[str]`: The decoded text.
        """
        return self.tokenizer.batch_decode(
            generated_outputs,
            skip_special_tokens=skip_special_tokens,
            clean_up_tokenization_spaces=clean_up_tokenization_spaces,
            **kwargs,
        )

    @property
    def model_input_names(self):
        tokenizer_input_names = self.tokenizer.model_input_names
        image_processor_input_names = self.image_processor.model_input_names
        names_from_processor = list(dict.fromkeys(tokenizer_input_names + image_processor_input_names))
        return names_from_processor + ["second_per_grid_ts"]



__all__ = ["KeyeProcessor", "KeyeProcessor_moonvit", "KeyeProcessor"]