image_folder: "/llm_reco_ssd/huqigen/dataset/wenjuan_sft/photo_0210_11w/"
excel_file_path: "/llm_reco_ssd/huqigen/0207_1k.xlsx"
hdfs_path: "viewfs://hadoop-lt-cluster/home/reco_kaiworks/dw/reco_kaiworks.db/reco_llm_wenjuan_comment_sample_0210_tmp"
parquet_path: "/llm_reco_ssd/huqigen/dataset/wenjuan_sft/photo_0210_11w/photo_0210_11w_sft_data.parquet"
txt_file_path: "/llm_reco_ssd/huqigen/recovlm/examples/infer/llm_model_api_req/0207_1k/deepseek_0207_1k_response_with_cmt_cot.txt"
hdfs_output_path: "viewfs://hadoop-lt-cluster/home/reco_wl/mpi/huqigen/recovlm_dataset/wenjuan_sft/0210_11w/"
data_source: "hdfs"
index_file: "/llm_reco_ssd/huqigen/dataset/wenjuan_sft/photo_0210_10w/recovlm_dataset_wenjuan_0210_10w.json"
num_shards: 2048
resize_image: false
num_workers: 40
source_name: "wenjuan_photo_0210_10w"