# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mmu import mmu_chat_gpt_pb2 as mmu_dot_mmu__chat__gpt__pb2


class MmuChatGptServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/mmu.nlp.MmuChatGptService/Chat',
                request_serializer=mmu_dot_mmu__chat__gpt__pb2.MmuChatGptRequest.SerializeToString,
                response_deserializer=mmu_dot_mmu__chat__gpt__pb2.MmuChatGptResponse.FromString,
                )
        self.Emb = channel.unary_unary(
                '/mmu.nlp.MmuChatGptService/Emb',
                request_serializer=mmu_dot_mmu__chat__gpt__pb2.MmuChatGptRequest.SerializeToString,
                response_deserializer=mmu_dot_mmu__chat__gpt__pb2.MmuChatGptEmbResponse.FromString,
                )


class MmuChatGptServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Emb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MmuChatGptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=mmu_dot_mmu__chat__gpt__pb2.MmuChatGptRequest.FromString,
                    response_serializer=mmu_dot_mmu__chat__gpt__pb2.MmuChatGptResponse.SerializeToString,
            ),
            'Emb': grpc.unary_unary_rpc_method_handler(
                    servicer.Emb,
                    request_deserializer=mmu_dot_mmu__chat__gpt__pb2.MmuChatGptRequest.FromString,
                    response_serializer=mmu_dot_mmu__chat__gpt__pb2.MmuChatGptEmbResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mmu.nlp.MmuChatGptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MmuChatGptService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mmu.nlp.MmuChatGptService/Chat',
            mmu_dot_mmu__chat__gpt__pb2.MmuChatGptRequest.SerializeToString,
            mmu_dot_mmu__chat__gpt__pb2.MmuChatGptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Emb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mmu.nlp.MmuChatGptService/Emb',
            mmu_dot_mmu__chat__gpt__pb2.MmuChatGptRequest.SerializeToString,
            mmu_dot_mmu__chat__gpt__pb2.MmuChatGptEmbResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
