# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mmu/mmu_chat_gpt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mmu import media_common_result_status_pb2 as mmu_dot_media__common__result__status__pb2
from mmu import media_common_pb2 as mmu_dot_media__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16mmu/mmu_chat_gpt.proto\x12\x07mmu.nlp\x1a$mmu/media_common_result_status.proto\x1a\x16mmu/media_common.proto\"\xf3\x01\n\x11MmuChatGptRequest\x12\x0b\n\x03\x62iz\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06req_id\x18\x03 \x01(\t\x12\x36\n\x06\x63onfig\x18\x04 \x03(\x0b\x32&.mmu.nlp.MmuChatGptRequest.ConfigEntry\x12\r\n\x05query\x18\x05 \x01(\t\x12\x15\n\rquery_history\x18\x06 \x03(\t\x12 \n\x03img\x18\x07 \x03(\x0b\x32\x13.mmu.common.ImgUnit\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"e\n\x12MmuChatGptResponse\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.mmu.common.ResultStatus\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x15\n\rquery_history\x18\x03 \x03(\t\"N\n\x15MmuChatGptEmbResponse\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.mmu.common.ResultStatus\x12\x0b\n\x03\x65mb\x18\x02 \x03(\x02\x32\x97\x01\n\x11MmuChatGptService\x12?\n\x04\x43hat\x12\x1a.mmu.nlp.MmuChatGptRequest\x1a\x1b.mmu.nlp.MmuChatGptResponse\x12\x41\n\x03\x45mb\x12\x1a.mmu.nlp.MmuChatGptRequest\x1a\x1e.mmu.nlp.MmuChatGptEmbResponseB9\n\x1d\x63om.kuaishou.protobuf.mmu.nlpB\x16MmuChatGptServiceProtoP\x01\x62\x06proto3')



_MMUCHATGPTREQUEST = DESCRIPTOR.message_types_by_name['MmuChatGptRequest']
_MMUCHATGPTREQUEST_CONFIGENTRY = _MMUCHATGPTREQUEST.nested_types_by_name['ConfigEntry']
_MMUCHATGPTRESPONSE = DESCRIPTOR.message_types_by_name['MmuChatGptResponse']
_MMUCHATGPTEMBRESPONSE = DESCRIPTOR.message_types_by_name['MmuChatGptEmbResponse']
MmuChatGptRequest = _reflection.GeneratedProtocolMessageType('MmuChatGptRequest', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _MMUCHATGPTREQUEST_CONFIGENTRY,
    '__module__' : 'mmu.mmu_chat_gpt_pb2'
    # @@protoc_insertion_point(class_scope:mmu.nlp.MmuChatGptRequest.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _MMUCHATGPTREQUEST,
  '__module__' : 'mmu.mmu_chat_gpt_pb2'
  # @@protoc_insertion_point(class_scope:mmu.nlp.MmuChatGptRequest)
  })
_sym_db.RegisterMessage(MmuChatGptRequest)
_sym_db.RegisterMessage(MmuChatGptRequest.ConfigEntry)

MmuChatGptResponse = _reflection.GeneratedProtocolMessageType('MmuChatGptResponse', (_message.Message,), {
  'DESCRIPTOR' : _MMUCHATGPTRESPONSE,
  '__module__' : 'mmu.mmu_chat_gpt_pb2'
  # @@protoc_insertion_point(class_scope:mmu.nlp.MmuChatGptResponse)
  })
_sym_db.RegisterMessage(MmuChatGptResponse)

MmuChatGptEmbResponse = _reflection.GeneratedProtocolMessageType('MmuChatGptEmbResponse', (_message.Message,), {
  'DESCRIPTOR' : _MMUCHATGPTEMBRESPONSE,
  '__module__' : 'mmu.mmu_chat_gpt_pb2'
  # @@protoc_insertion_point(class_scope:mmu.nlp.MmuChatGptEmbResponse)
  })
_sym_db.RegisterMessage(MmuChatGptEmbResponse)

_MMUCHATGPTSERVICE = DESCRIPTOR.services_by_name['MmuChatGptService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.kuaishou.protobuf.mmu.nlpB\026MmuChatGptServiceProtoP\001'
  _MMUCHATGPTREQUEST_CONFIGENTRY._options = None
  _MMUCHATGPTREQUEST_CONFIGENTRY._serialized_options = b'8\001'
  _MMUCHATGPTREQUEST._serialized_start=98
  _MMUCHATGPTREQUEST._serialized_end=341
  _MMUCHATGPTREQUEST_CONFIGENTRY._serialized_start=296
  _MMUCHATGPTREQUEST_CONFIGENTRY._serialized_end=341
  _MMUCHATGPTRESPONSE._serialized_start=343
  _MMUCHATGPTRESPONSE._serialized_end=444
  _MMUCHATGPTEMBRESPONSE._serialized_start=446
  _MMUCHATGPTEMBRESPONSE._serialized_end=524
  _MMUCHATGPTSERVICE._serialized_start=527
  _MMUCHATGPTSERVICE._serialized_end=678
# @@protoc_insertion_point(module_scope)
