output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/zhangzixing/recovlm_dataset_table/gpt4o_infovqa_ocr
split_size: 536870912
dataset:
  class_name: ImagesDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/infoVQA/human_download/infographicsvqa_images
    img_max_size: 1080
converter:
  class_name: GPT4oConverter
  kwargs:
    prompt: 请仔细观察这张图片，识别图片中的全部文字，并按照顺序输出，注意：尽可能保留图片中的全部文字内容，不要输出其他文字
    train_prompts:
      - 请识别图片中的全部文字，并按照顺序输出。
      - 你能识别这张图片中的所有文字并按顺序输出吗？
      - 能否识别图片中的所有文字，并按顺序输出？
      - 请识别并按顺序输出图片中的所有文字。
      - 请你识别这张图片中的全部文字，并按顺序输出。
      - Could you recognize all the text in the image and output it in order?
      - Please identify all the text in the image and output it sequentially.
      - Can you recognize all the text in this image and output it in the correct order?
      - Could you identify all the text from the image and provide it in order?
      - Please recognize and output all the text in the image in the correct sequence.
    source: gpt4o_infovqa_ocr