output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/zhangzixing/recovlm_dataset_table/gpt4o_infovqa_qa
split_size: 536870912
dataset:
  class_name: ImagesDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/infoVQA/human_download/infographicsvqa_images
    img_max_size: 1080
converter:
  class_name: GPT4oConverter
  kwargs:
    prompt: '我是一名教师，想锻炼小朋友在不同语言下的图表内容识别与理解能力，请仔细观察这张表格，帮我抽取其中的关键信息生成10个问题。注意：1. 问题和答案保留图表中的原始文本，不要进行翻译。2. 以json格式返回问题和答案，格式为：[    {"question": "abc", "answer": "efg"},\n    {"question": "123", "answer": "456"}\n]。3. 只返回json数据，不要返回其他文字'
    train_prompts:
      - 请仔细查看这张图片，帮我提取其中的关键信息生成10个问题。
      - 你能根据这张图片提取关键信息并生成10个问题吗？
      - 能否查看这张图片并提取关键信息生成10个问题？
      - 请你查看这张图片，提取关键信息并生成10个问题。
      - 请根据这张图片提取关键信息并生成10个问题。
      - 请仔细观察这张图片，提取其中的关键信息并生成10个问题。
      - 能否帮我从这张图片中提取关键信息并生成10个问题？
      - 请你从这张图片中提取关键信息并生成10个问题。
      - 请查看这张图片，提取关键信息并生成10个问题。
      - 能否根据这张图片提取关键信息并生成10个问题？
      - Could you carefully examine this image and extract key information to generate 10 questions?
      - Please take a close look at this image and extract key information to create 10 questions.
      - Can you extract key information from this image and generate 10 questions?
      - Could you look at this image and extract key information to form 10 questions?
      - Please examine this image and extract key information to generate 10 questions.
      - Could you analyze this image and extract key information to create 10 questions?
      - Can you help me extract key information from this image and generate 10 questions?
      - Please extract key information from this image and generate 10 questions.
      - Could you review this image and extract key information to form 10 questions?
      - Can you look at this image and extract key information to generate 10 questions?
    source: gpt4o_infovqa_qa