# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mmu/media_common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mmu/media_common.proto',
  package='mmu.common',
  syntax='proto3',
  serialized_options=b'\n\027com.kuaishou.mmu.commonB\004Unit',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16mmu/media_common.proto\x12\nmmu.common\"\x8f\x02\n\x07ImgUnit\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12&\n\x04type\x18\x03 \x01(\x0e\x32\x18.mmu.common.ImgUnit.Type\x12\x0b\n\x03txt\x18\x04 \x01(\t\x12\r\n\x05width\x18\x05 \x01(\r\x12\x0e\n\x06height\x18\x06 \x01(\r\x12\x36\n\ninput_text\x18\x07 \x03(\x0b\x32\".mmu.common.ImgUnit.InputTextEntry\x1a\x30\n\x0eInputTextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"+\n\x04Type\x12\x08\n\x04HEAD\x10\x00\x12\x0e\n\nBACKGROUND\x10\x01\x12\t\n\x05\x46RAME\x10\x02\x42\x1f\n\x17\x63om.kuaishou.mmu.commonB\x04Unitb\x06proto3'
)



_IMGUNIT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='mmu.common.ImgUnit.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEAD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BACKGROUND', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FRAME', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=267,
  serialized_end=310,
)
_sym_db.RegisterEnumDescriptor(_IMGUNIT_TYPE)


_IMGUNIT_INPUTTEXTENTRY = _descriptor.Descriptor(
  name='InputTextEntry',
  full_name='mmu.common.ImgUnit.InputTextEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mmu.common.ImgUnit.InputTextEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mmu.common.ImgUnit.InputTextEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=265,
)

_IMGUNIT = _descriptor.Descriptor(
  name='ImgUnit',
  full_name='mmu.common.ImgUnit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mmu.common.ImgUnit.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='mmu.common.ImgUnit.image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='mmu.common.ImgUnit.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='txt', full_name='mmu.common.ImgUnit.txt', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='mmu.common.ImgUnit.width', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='mmu.common.ImgUnit.height', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_text', full_name='mmu.common.ImgUnit.input_text', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IMGUNIT_INPUTTEXTENTRY, ],
  enum_types=[
    _IMGUNIT_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=310,
)

_IMGUNIT_INPUTTEXTENTRY.containing_type = _IMGUNIT
_IMGUNIT.fields_by_name['type'].enum_type = _IMGUNIT_TYPE
_IMGUNIT.fields_by_name['input_text'].message_type = _IMGUNIT_INPUTTEXTENTRY
_IMGUNIT_TYPE.containing_type = _IMGUNIT
DESCRIPTOR.message_types_by_name['ImgUnit'] = _IMGUNIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImgUnit = _reflection.GeneratedProtocolMessageType('ImgUnit', (_message.Message,), {

  'InputTextEntry' : _reflection.GeneratedProtocolMessageType('InputTextEntry', (_message.Message,), {
    'DESCRIPTOR' : _IMGUNIT_INPUTTEXTENTRY,
    '__module__' : 'mmu.media_common_pb2'
    # @@protoc_insertion_point(class_scope:mmu.common.ImgUnit.InputTextEntry)
    })
  ,
  'DESCRIPTOR' : _IMGUNIT,
  '__module__' : 'mmu.media_common_pb2'
  # @@protoc_insertion_point(class_scope:mmu.common.ImgUnit)
  })
_sym_db.RegisterMessage(ImgUnit)
_sym_db.RegisterMessage(ImgUnit.InputTextEntry)


DESCRIPTOR._options = None
_IMGUNIT_INPUTTEXTENTRY._options = None
# @@protoc_insertion_point(module_scope)
