# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mmu/mmu_chat_gpt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tools.gpt_tools.mmu import media_common_result_status_pb2 as mmu_dot_media__common__result__status__pb2
from tools.gpt_tools.mmu import media_common_pb2 as mmu_dot_media__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mmu/mmu_chat_gpt.proto',
  package='mmu.nlp',
  syntax='proto3',
  serialized_options=b'\n\035com.kuaishou.protobuf.mmu.nlpB\026MmuChatGptServiceProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16mmu/mmu_chat_gpt.proto\x12\x07mmu.nlp\x1a$mmu/media_common_result_status.proto\x1a\x16mmu/media_common.proto\"\xf3\x01\n\x11MmuChatGptRequest\x12\x0b\n\x03\x62iz\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06req_id\x18\x03 \x01(\t\x12\x36\n\x06\x63onfig\x18\x04 \x03(\x0b\x32&.mmu.nlp.MmuChatGptRequest.ConfigEntry\x12\r\n\x05query\x18\x05 \x01(\t\x12\x15\n\rquery_history\x18\x06 \x03(\t\x12 \n\x03img\x18\x07 \x03(\x0b\x32\x13.mmu.common.ImgUnit\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"e\n\x12MmuChatGptResponse\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.mmu.common.ResultStatus\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\x12\x15\n\rquery_history\x18\x03 \x03(\t\"N\n\x15MmuChatGptEmbResponse\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.mmu.common.ResultStatus\x12\x0b\n\x03\x65mb\x18\x02 \x03(\x02\x32\xe0\x01\n\x11MmuChatGptService\x12?\n\x04\x43hat\x12\x1a.mmu.nlp.MmuChatGptRequest\x1a\x1b.mmu.nlp.MmuChatGptResponse\x12\x41\n\x03\x45mb\x12\x1a.mmu.nlp.MmuChatGptRequest\x1a\x1e.mmu.nlp.MmuChatGptEmbResponse\x12G\n\nStreamChat\x12\x1a.mmu.nlp.MmuChatGptRequest\x1a\x1b.mmu.nlp.MmuChatGptResponse0\x01\x42\x39\n\x1d\x63om.kuaishou.protobuf.mmu.nlpB\x16MmuChatGptServiceProtoP\x01\x62\x06proto3'
  ,
  dependencies=[mmu_dot_media__common__result__status__pb2.DESCRIPTOR,mmu_dot_media__common__pb2.DESCRIPTOR,])




_MMUCHATGPTREQUEST_CONFIGENTRY = _descriptor.Descriptor(
  name='ConfigEntry',
  full_name='mmu.nlp.MmuChatGptRequest.ConfigEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mmu.nlp.MmuChatGptRequest.ConfigEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mmu.nlp.MmuChatGptRequest.ConfigEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=341,
)

_MMUCHATGPTREQUEST = _descriptor.Descriptor(
  name='MmuChatGptRequest',
  full_name='mmu.nlp.MmuChatGptRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='biz', full_name='mmu.nlp.MmuChatGptRequest.biz', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='mmu.nlp.MmuChatGptRequest.session_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='req_id', full_name='mmu.nlp.MmuChatGptRequest.req_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='mmu.nlp.MmuChatGptRequest.config', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query', full_name='mmu.nlp.MmuChatGptRequest.query', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_history', full_name='mmu.nlp.MmuChatGptRequest.query_history', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='img', full_name='mmu.nlp.MmuChatGptRequest.img', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MMUCHATGPTREQUEST_CONFIGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=341,
)


_MMUCHATGPTRESPONSE = _descriptor.Descriptor(
  name='MmuChatGptResponse',
  full_name='mmu.nlp.MmuChatGptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='mmu.nlp.MmuChatGptResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='answer', full_name='mmu.nlp.MmuChatGptResponse.answer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query_history', full_name='mmu.nlp.MmuChatGptResponse.query_history', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=444,
)


_MMUCHATGPTEMBRESPONSE = _descriptor.Descriptor(
  name='MmuChatGptEmbResponse',
  full_name='mmu.nlp.MmuChatGptEmbResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='mmu.nlp.MmuChatGptEmbResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emb', full_name='mmu.nlp.MmuChatGptEmbResponse.emb', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=524,
)

_MMUCHATGPTREQUEST_CONFIGENTRY.containing_type = _MMUCHATGPTREQUEST
_MMUCHATGPTREQUEST.fields_by_name['config'].message_type = _MMUCHATGPTREQUEST_CONFIGENTRY
_MMUCHATGPTREQUEST.fields_by_name['img'].message_type = mmu_dot_media__common__pb2._IMGUNIT
_MMUCHATGPTRESPONSE.fields_by_name['status'].message_type = mmu_dot_media__common__result__status__pb2._RESULTSTATUS
_MMUCHATGPTEMBRESPONSE.fields_by_name['status'].message_type = mmu_dot_media__common__result__status__pb2._RESULTSTATUS
DESCRIPTOR.message_types_by_name['MmuChatGptRequest'] = _MMUCHATGPTREQUEST
DESCRIPTOR.message_types_by_name['MmuChatGptResponse'] = _MMUCHATGPTRESPONSE
DESCRIPTOR.message_types_by_name['MmuChatGptEmbResponse'] = _MMUCHATGPTEMBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MmuChatGptRequest = _reflection.GeneratedProtocolMessageType('MmuChatGptRequest', (_message.Message,), {

  'ConfigEntry' : _reflection.GeneratedProtocolMessageType('ConfigEntry', (_message.Message,), {
    'DESCRIPTOR' : _MMUCHATGPTREQUEST_CONFIGENTRY,
    '__module__' : 'mmu.mmu_chat_gpt_pb2'
    # @@protoc_insertion_point(class_scope:mmu.nlp.MmuChatGptRequest.ConfigEntry)
    })
  ,
  'DESCRIPTOR' : _MMUCHATGPTREQUEST,
  '__module__' : 'mmu.mmu_chat_gpt_pb2'
  # @@protoc_insertion_point(class_scope:mmu.nlp.MmuChatGptRequest)
  })
_sym_db.RegisterMessage(MmuChatGptRequest)
_sym_db.RegisterMessage(MmuChatGptRequest.ConfigEntry)

MmuChatGptResponse = _reflection.GeneratedProtocolMessageType('MmuChatGptResponse', (_message.Message,), {
  'DESCRIPTOR' : _MMUCHATGPTRESPONSE,
  '__module__' : 'mmu.mmu_chat_gpt_pb2'
  # @@protoc_insertion_point(class_scope:mmu.nlp.MmuChatGptResponse)
  })
_sym_db.RegisterMessage(MmuChatGptResponse)

MmuChatGptEmbResponse = _reflection.GeneratedProtocolMessageType('MmuChatGptEmbResponse', (_message.Message,), {
  'DESCRIPTOR' : _MMUCHATGPTEMBRESPONSE,
  '__module__' : 'mmu.mmu_chat_gpt_pb2'
  # @@protoc_insertion_point(class_scope:mmu.nlp.MmuChatGptEmbResponse)
  })
_sym_db.RegisterMessage(MmuChatGptEmbResponse)


DESCRIPTOR._options = None
_MMUCHATGPTREQUEST_CONFIGENTRY._options = None

_MMUCHATGPTSERVICE = _descriptor.ServiceDescriptor(
  name='MmuChatGptService',
  full_name='mmu.nlp.MmuChatGptService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=527,
  serialized_end=751,
  methods=[
  _descriptor.MethodDescriptor(
    name='Chat',
    full_name='mmu.nlp.MmuChatGptService.Chat',
    index=0,
    containing_service=None,
    input_type=_MMUCHATGPTREQUEST,
    output_type=_MMUCHATGPTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Emb',
    full_name='mmu.nlp.MmuChatGptService.Emb',
    index=1,
    containing_service=None,
    input_type=_MMUCHATGPTREQUEST,
    output_type=_MMUCHATGPTEMBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamChat',
    full_name='mmu.nlp.MmuChatGptService.StreamChat',
    index=2,
    containing_service=None,
    input_type=_MMUCHATGPTREQUEST,
    output_type=_MMUCHATGPTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MMUCHATGPTSERVICE)

DESCRIPTOR.services_by_name['MmuChatGptService'] = _MMUCHATGPTSERVICE

# @@protoc_insertion_point(module_scope)
