output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/zhangzixing/recovlm_dataset_table/gpt4o_xfund_json_q
split_size: 536870912
dataset:
  class_name: ImagesDataset
  kwargs:
    path: /llm_reco_ssd/zhangzixing/XFUND_img
    img_max_size: 1080
converter:
  class_name: GPT4oConverter
  kwargs:
    prompt: '我是一名教师，想锻炼小朋友在不同语言下的图表内容识别与理解能力，请仔细观察这张表格，帮我抽取其中的关键信息生成10个问题。注意：1. 问题和答案保留图表中的原始文本，不要进行翻译。2. 以json格式返回问题和答案，格式为：[    {"question": "abc", "answer": "efg"},\n    {"question": "123", "answer": "456"}\n]。3. 只返回json数据，不要返回其他文字'
    train_prompts:
      - 请仔细查看这张表格，帮我提取其中的关键信息生成10个问题。
      - 你能根据这张表格提取关键信息并生成10个问题吗？
      - 能否根据这张表格创建10个问题，提取其中的关键信息？
      - 请根据这张表格提取关键信息并生成10个问题。
      - 请你观察这张表格，并提取其中的关键信息生成10个问题。
      - Could you carefully observe this table and extract the key information to generate 10 questions?
      - Please take a close look at this table and create 10 questions by extracting the key information.
      - Can you generate 10 questions based on this table by extracting the key information?
      - Could you create 10 questions from this table by extracting the key information?
      - Please examine this table and generate 10 questions by closely matching its key information.
    source: gpt4o_xfund_json_q