output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/zhangzixing/recovlm_dataset_table/gpt4o_xfund_html
split_size: 536870912
dataset:
  class_name: ImagesDataset
  kwargs:
    path: /llm_reco_ssd/zhangzixing/XFUND_img
    img_max_size: 1080
converter:
  class_name: GPT4oConverter
  kwargs:
    prompt: 请仔细观察这张图片，针对这张图片生成html代码，要求尽可能还原图片中的格式和内容，忽略图中的条形码。注意，只输出html代码，不要包含其他文字。
    train_prompts:
      - 请仔细查看这张图片，并生成对应的HTML代码，尽量还原图片中的格式。
      - 你能根据这张图片生成HTML代码吗？请尽量保持格式一致。
      - 能否根据这张图片创建一个HTML代码，尽量还原其格式？
      - 请根据这张图片生成HTML代码，尽可能保持格式不变。
      - 请你观察这张图片，并生成相应的HTML代码，尽量还原图片的格式。
      - Could you carefully observe this image and generate HTML code that replicates its format as closely as possible?
      - Please take a close look at this image and create HTML code that mirrors the format of the image.
      - Can you generate HTML code based on this image, ensuring the format is as close as possible?
      - Could you create HTML code from this image, trying to replicate the format as accurately as possible?
      - Please examine this image and generate HTML code that closely matches its format.
    source: gpt4o_xfund_html