output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/text/General_QA/infinity_instruct_7m
split_size: 268_435_456
dataset:
  class_name: ParquetDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/Infinity-Instruct/7M
    columns:
      - conversations
      - source
converter:
  class_name: InfinityInstructConverter
  kwargs: {}
