output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/chuchenglong/asr_interleave
split_size: 536870912
dataset:
  class_name: JsonDataset
  kwargs:
    path: /llm_reco/chuchenglong/R3/asr_meta/merged_asr_meta.json
converter:
  class_name: ASRInterConverter
  kwargs:
    source: asr_interleave