output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/caption/Detailed_Caption
split_size: 268_435_456
dataset:
  class_name: JsonDataset
  kwargs:
    path: /llm_reco/luoxinchen/dataset/Detailed_Caption/Detailed_Caption/detailed_caption.json
converter:
  class_name: OpenImagesCaptionConverter
  kwargs:
    source: detailed_caption
