output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/caption/laion_zh
split_size: 268_435_456
dataset:
  class_name: ParquetDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/laion2B-multi-zh/laion2B-multi-chinese-subset/data
    columns:
      - similarity
      - TEXT
      - URL
converter:
  class_name: BlobstoreCaptionConverter
  kwargs:
    bucket_name: upload-dujuan-video
    key_col: md5
    caption_col: TEXT
    source: laion_zh
    md5_col: URL
