output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_stage2/pubtabnet
split_size: 67108864
dataset:
  class_name: PubTabNetDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/pubtabnet/pubtabnet
converter:
  class_name: PubTabNetConverter
  kwargs: 
    source: pubtabnet