output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/caption/datacomp
split_size: 268_435_456
dataset:
  class_name: WebDataset
  kwargs:
    index_list:
      - /llm_reco_ssd/luoxinchen/dataset/datacomp/large/index.json
converter:
  class_name: WebDatasetCaptionConverter
  kwargs:
    source: datacomp