output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/vit/ShareGPT4V
split_size: 268_435_456
dataset:
  class_name: ParquetDataset
  kwargs:
    path: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/caption/ShareGPT4V
  columns:
    - images
    - messages
converter:
  class_name: OvitConverter
  kwargs:
    source: ShareGPT4V
