output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/caption/laion2b_coco
split_size: 268_435_456
dataset:
  class_name: ParquetDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/laion-coco/laion-coco
    columns:
      - similarity
      - top_caption
      - URL
converter:
  class_name: BlobstoreCaptionConverter
  kwargs:
    bucket_name: upload-dujuan-video
    key_col: md5
    caption_col: top_caption
    source: laion_coco
    md5_col: URL
