output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/caption/OpenImages-Caption
split_size: 268_435_456
dataset:
  class_name: ParquetDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/OpenImages/open-images-captions-micro/data
    columns:
      - caption
      - image
converter:
  class_name: OpenImagesCaptionConverter
  kwargs:
    source: OpenImages-Caption
