output_dir: /llm_reco_ssd/luoxinchen/dataset/Stage2/DenseFusion-4V-100k
shard_size: 1000
dataset:
  class_name: JsonlDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/DenseFusion-1M/DenseFusion-4V-100k/DenseFusion-4V-100k.jsonl
converter:
  class_name: DenseFusionConverter
  kwargs:
    image_dir: /llm_reco_ssd/luoxinchen/dataset/DenseFusion-1M/images
    source: dense_fusion_4v_100k
    prompts:
      - Can you describe this picture for me?
      - Please tell me what you see in this image.
      - Could you explain what is happening in this photo?
      - Would you mind describing the details of this picture?
      - Can you give me a description of this image?
      - Please describe the scene in this photo.
      - What can you see in this picture?
      - Could you provide a description of this image?
      - Can you explain the contents of this picture?
      - Would you please describe what’s in this photo?
      - How would you describe this image?
      - Can you paint a picture with words for this photo?
      - What details stand out to you in this picture?
      - Could you narrate what this image depicts?
      - What’s your interpretation of this photo?