output_dir: /llm_reco_ssd/luoxinchen/dataset/Stage2/Docmatrix
shard_size: 10000
dataset:
  class_name: ParquetDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/Docmatix/Docmatix/data
    columns:
      - images
      - texts
converter:
  class_name: DocmatrixConverter
  kwargs: {}