output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_cleaned/coyo_20250124
split_size: 268_435_456
dataset:
  class_name: ParquetDataset
  kwargs:
    path: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_original/single_image/Captioning/coyo700m
pre_filters:
  - class_name: ImageSizeFilter
    kwargs:
      min_pixel: 256
      max_pixel: 4_194_304
      min_aspect_ratio: 0.1
      max_aspect_ratio: 10
converters:
  - class_name: CleanHtmlConverter
    kwargs: {}
  - class_name: CleanLinksConverter
    kwargs: {}
post_filters:
  - class_name: AlphaNumericFilter
    kwargs:
      min_ratio: 0.2
      max_ratio: 1.0
  - class_name: SpecialCharactersFilter
    kwargs:
      min_ratio: 0.0
      max_ratio: 0.3
  - class_name: TextLengthFilter
    kwargs:
      min_length: 3
      max_length: 1024
