output_dir: /llm_reco_ssd/maosiyang/dataset/kwai_video_category/20250317
split_size: 32_000_000
dataset:
  class_name: ParquetDataset
  kwargs:
    path: viewfs://hadoop-lt-cluster/home/reco_kaiworks/dw/reco_kaiworks.db/llm_video_catgory_train_v1/p_date=0215-0316
    columns:
      - photo_id
      - first_level_category_name
      - first_level_category_prob
      - second_level_category_name
      - second_level_category_prob
      - third_level_category_name
      - third_level_category_prob
      - fourth_level_category_name
      - fourth_level_category_prob
converter:
  class_name: KwaiVideoCategoryConverter
  kwargs:
    source: kwai_video_title_caption
    video_dir: /llm_reco/luoxinchen/dataset/InHouse/Photo/20250215/480p_60s_4fps_v2/
    ffmpeg_args: -vf scale='if(gt(iw,ih),min(480,iw),-2)':'if(gt(ih,iw),min(480,ih),-2)' -r 4 -t 60 -c:a aac -c:v libx264 -b:a 55k -pix_fmt yuv420p -probesize 200M -analyzeduration 200M
    prompts:
      - "你是一个短视频内容分析专家，现在请你为这个视频分类，总共有四个级别的分类，请你依次判断这个视频在四层级别中分别属于哪个类别，如果视频分类模糊可以在前几层提前终止。"
      - "你是一位短视频内容分析专家，请为这个视频进行分类。视频分类共有四个级别，请依次判断视频在每个级别中属于哪个类别。如果在前几层级别中已经能够明确分类，可以提前终止分类过程。"
      - "请作为短视频内容分析专家，请你为这个视频进行分类。视频分类分为四个层级，请逐层判断视频所属类别。如果在某个层级已经能够确定视频分类，可以提前结束分类。"
      - "你是一位短视频内容分析专家，请对这个视频进行分类。视频分类共有四个层级，请依次判断视频在每个层级中的类别。如果在前几个层级已经能够明确视频分类，可以提前结束分类过程。"