output_dir: /llm_reco_ssd/maosiyang/dataset/kwai_video_title_caption/20250317
shard_size: 10000
dataset:
  class_name: ParquetDataset
  kwargs:
    path: viewfs://hadoop-lt-cluster/home/reco_kaiworks/dw/reco_kaiworks.db/llm_video_name_caption_train_v1/p_date=0215-0316
    columns:
      - photo_id
      - caption_clean
      - title
converter:
  class_name: KwaiVideoTitleCaptionConverter
  kwargs:
    source: kwai_video_title_caption
    video_dir: /llm_reco/luoxinchen/dataset/InHouse/Photo/20250215/480p_60s_4fps_v2/
    ffmpeg_args: -vf scale='if(gt(iw,ih),min(480,iw),-2)':'if(gt(ih,iw),min(480,ih),-2)' -r 4 -t 60 -c:a aac -c:v libx264 -b:a 55k -pix_fmt yuv420p -probesize 200M -analyzeduration 200M
    prompts:
      - "请写出这个视频的标题和描述。"