output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/maosiyang/kwai_video/shuffle/train/v1/
split_size: 42_000_000
dataset:
  class_name: ParquetDataset
  kwargs:
    path: 
    columns:
      - photo_id
converter:
  class_name: KwaiVideoShuffleConverter
  kwargs:
    source: kwai_video_title_caption
    video_dir: /llm_reco/luoxinchen/dataset/InHouse/Photo/20250215/480p_60s_4fps_v2/
    ffmpeg_args: -vf scale='if(gt(iw,ih),min(480,iw),-2)':'if(gt(ih,iw),min(480,ih),-2)' -r 4 -t 60 -c:a aac -c:v libx264 -b:a 55k -pix_fmt yuv420p -probesize 200M -analyzeduration 200M
    prompts:
      - "这是一个被打乱的视频抽帧，请你输出它的正确排列。"
      - "请提供这个乱序视频抽帧的正确排列。"
      - "请排列出以下图片的正确顺序。"