output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/huqigen/recovlm_dataset/wenjuan_sft/20250304wenjuan_benchmark_dataset_v3
split_size: 536870912
dataset:
  class_name: ParquetDataset
  kwargs:
    path: viewfs://hadoop-lt-cluster/home/reco_kaiworks/dw/reco_kaiworks.db/reco_llm_wenjuan_comment_sample_20250304_tmp_shuffle
    columns:
      - photo_id
      - wenjuan_type
      - caption
      - user_comment
      - ocr
      - asr

converter:
  class_name: KwaiWenJuanCaptionFrameConverter
  kwargs:
    source: kwai_wenjuan_photo_comment_with_cot
    frame_dir: /llm_reco_ssd/huqigen/dataset/wenjuan_sft/photo_0210_11w/
    video_dir: /llm_reco/luoxinchen/dataset/InHouse/Photo/20250215/480p_60s_4fps_v2/
    test_id_file_path: /llm_reco_ssd/huqigen/dataset/wenjuan_sft/photo_0210_11w/test_photo_id.csv
    ffmpeg_args: -vf scale='if(gt(iw,ih),min(480,iw),-2)':'if(gt(ih,iw),min(480,ih),-2)' -r 4 -t 60 -c:a aac -c:v libx264 -b:a 55k -pix_fmt yuv420p -probesize 200M -analyzeduration 200M
    prompts:
      - "你是一个短视频内容分析专家，现在需要你判断一下平台内用户对短视频的满意度，我们会提供原始视频内容(内容特征将以OCR/ASR/图像数据呈现)。请在回答的最后给出最终的满意度判断结果，只包含满意/不满意两种类型，格式为：【结果：满意/不满意】"
    cot_txt_file_path: /mmu_mllm_hdd/dengjiaxin03/11w_data_infer_result_with_all_cmt
    max_frames_per_video: 20
    enable_debug: true
    filter_by_llm_label: false
    enable_llm_response: false