output_dir: /llm_reco_ssd/luoxinchen/dataset/Stage2/LLaVA-CC3M-Pretrain-595K
shard_size: 1000
dataset:
  class_name: JsonDataset
  kwargs:
    path: /llm_reco_ssd/luoxinchen/dataset/LLaVA-CC3M-Pretrain-595K/chat.json
converter:
  class_name: LlavaCC3MPretrainConverter
  kwargs:
    image_dir: /llm_reco_ssd/luoxinchen/dataset/LLaVA-CC3M-Pretrain-595K
    source: llava_cc3m_pretrain_595k