output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_stage2_shuffle/recovlm_dataset_no_interleave_shuffle_resample_20250120
split_size: 536870912
dataset:
  class_name: ParquetDataset
  kwargs:
    path: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_no_interleave_shuffle
converter:
  class_name: ResampleConverter
  kwargs:
    sample_config:
      plotqa: 0.2
      ImageNet-21K: 0.3
      PDFA: 0.4
      Google-Landmarks: 0.8