output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_sft/vlm_sft_pure_text
split_size: 536870912
dataset:
  class_name: VlmTextJsonl
  kwargs:
    path:
      /llm_reco_ssd/luoxinchen/dataset/VLM-SFT/clean_data.jsonl
converter:
  class_name: VlmSftTextConverter
  kwargs: {}
