output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/zhangzixing/recovlm_dataset_table/gpt4o_sroie_markdown
split_size: 536870912
dataset:
  class_name: ImagesDataset
  kwargs:
    path: /llm_reco_ssd/renlejian/raw_datasets/OCR/SROIE/SROIE2019/0325updated.task2train
    img_max_size: 1080
converter:
  class_name: GPT4oConverter
  kwargs:
    prompt: 请仔细观察这张图片，针对这张图片生成Markdown代码，要求尽可能还原图片中的格式和内容，忽略图中的条形码。注意，只输出对应的markdown代码，不要包含其他文字。
    train_prompts:
      - 请根据这张图片生成Markdown代码，尽可能保持格式和内容不变。
      - 你能根据这张图片生成Markdown代码吗？请尽量保持格式和内容一致。
      - 能否根据这张图片创建一个Markdown代码，尽量还原其格式和内容？
      - 请生成这张图片的Markdown代码，尽量保持格式和内容不变。
      - 请你根据这张图片生成Markdown代码，尽量还原图片的格式和内容。
      - 请仔细查看这张图片，并生成对应的Markdown代码，尽量还原图片中的格式和内容。
      - 能否根据这张图片生成Markdown代码，并尽量保持格式和内容一致？
      - 请根据这张图片生成Markdown代码，尽量还原其格式和内容。
      - 请你观察这张图片，并生成相应的Markdown代码，尽量还原图片的格式和内容。
      - 请根据这张图片生成Markdown代码，尽可能保持其格式和内容。
      - Could you generate Markdown code based on this image, ensuring the format and content are as close as possible?
      - Please create Markdown code from this image, trying to replicate the format and content as accurately as possible.
      - Can you generate Markdown code from this image, keeping the format and content unchanged?
      - Could you carefully observe this image and generate Markdown code that replicates its format and content as closely as possible?
      - Please take a close look at this image and create Markdown code that mirrors the format and content of the image.
      - Can you generate Markdown code based on this image, ensuring the format and content are as close as possible?
      - Could you create Markdown code from this image, trying to replicate the format and content as accurately as possible?
      - Please examine this image and generate Markdown code that closely matches its format and content.
      - Could you review this image and generate Markdown code that maintains the format and content?
      - Can you look at this image and generate Markdown code that keeps the format and content unchanged?
    source: gpt4o_sroie_markdown