output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/zhangzixing/recovlm_dataset_table/gpt4o_sroie_json
split_size: 536870912
dataset:
  class_name: ImagesDataset
  kwargs:
    path: /llm_reco_ssd/renlejian/raw_datasets/OCR/SROIE/SROIE2019/0325updated.task2train
    img_max_size: 1080
converter:
  class_name: GPT4oConverter
  kwargs:
    prompt: '请使用json格式，尽可能详细的描述图片中的内容，注意：只保留json内容，不输出其他文字'
    train_prompts:
      - 请使用json格式，尽可能详细地描述图片中的内容。
      - 你能用json格式详细描述这张图片的内容吗？
      - 能否使用json格式来详细描述图片中的内容？
      - 请用json格式描述这张图片的内容，尽量详细。
      - 请你使用json格式，详细描述图片中的内容。
      - 请用json格式尽可能详细地描述这张图片。
      - 能否帮我用json格式详细描述这张图片的内容？
      - 请你用json格式详细描述图片中的内容。
      - 请使用json格式来描述这张图片的内容，尽量详细。
      - 能否用json格式尽可能详细地描述图片中的内容？
      - Could you use JSON format to describe the content of the image in detail?
      - Please describe the content of this image in detail using JSON format.
      - Can you describe the content of this image in detail using JSON format?
      - Could you use JSON format to provide a detailed description of the image's content?
      - Please use JSON format to describe the image's content as detailed as possible.
      - Could you help me describe the content of this image in detail using JSON format?
      - Please use JSON format to give a detailed description of the content in the image.
      - Could you provide a detailed description of the image content using JSON format?
      - Can you use JSON format to describe the image content in detail?
      - Please use JSON format to thoroughly describe the content of this image.
    source: gpt4o_sroie_json