output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/zhangzixing/recovlm_dataset_table/gpt4o_sroie_html
split_size: 536870912
dataset:
  class_name: ImagesDataset
  kwargs:
    path: /llm_reco_ssd/renlejian/raw_datasets/OCR/SROIE/SROIE2019/0325updated.task2train
    img_max_size: 1080
converter:
  class_name: GPT4oConverter
  kwargs:
    prompt: 请仔细观察这张图片，针对这张图片生成html代码，要求尽可能还原图片中的格式和内容，忽略图中的条形码。注意，只输出html代码，不要包含其他文字。
    train_prompts:
      - 你能根据这张图片生成HTML代码吗？请尽量保持格式一致。
      - 请根据这张图片生成HTML代码，尽量保持格式一致。
      - 能否根据这张图片生成HTML代码，并尽量保持格式一致？
      - 请你根据这张图片生成HTML代码，尽量保持格式一致。
      - 请生成这张图片的HTML代码，尽量保持格式一致。
      - 能否帮我根据这张图片生成HTML代码，并尽量保持格式一致？
      - 请你根据这张图片生成HTML代码，尽量还原其格式。
      - 请根据这张图片生成HTML代码，尽量还原格式。
      - 能否根据这张图片生成HTML代码，尽量保持其格式一致？
      - 请你根据这张图片生成HTML代码，尽量保持其格式一致。
      - Could you generate HTML code based on this image, ensuring the format is consistent?
      - Please create HTML code from this image, trying to keep the format consistent.
      - Can you generate HTML code from this image, keeping the format consistent?
      - Could you create HTML code based on this image, ensuring the format remains the same?
      - Please generate HTML code from this image, trying to maintain the same format.
      - Could you help me generate HTML code from this image, ensuring the format is consistent?
      - Please create HTML code from this image, maintaining the same format.
      - Could you provide HTML code based on this image, keeping the format consistent?
      - Can you create HTML code from this image, ensuring the format remains unchanged?
      - Please generate HTML code from this image, ensuring the format is consistent.
    source: gpt4o_sroie_html