FROM registry.corp.kuaishou.com/kml/cuda:11.8.0-cudnn8-devel-ubuntu22.04

RUN export http_proxy=http://oversea-squid4.sgp.txyun:11080 https_proxy=http://oversea-squid4.sgp.txyun:11080 && \
    apt-get update && apt-get install -y \
    build-essential \
    curl \
    tmux \
    vim \
    software-properties-common \
    python3-pip \
    python3.10-venv

RUN mkdir -p /root/.pip && \
    echo "[global]\nindex-url = https://pypi.corp.kuaishou.com/kuaishou/prod/+simple/" > /root/.pip/pip.conf
    
RUN pip3 install build