FROM registry.corp.kuaishou.com/kml-supercomputing-project/pytorch:2.5.1_cuda11.8.0_python3.12.0

ENV DEBIAN_FRONTEND=noninteractive

RUN export http_proxy=http://oversea-squid4.sgp.txyun:11080 https_proxy=http://oversea-squid4.sgp.txyun:11080 && \
    apt-get update && \
    apt-get install -y tzdata && \
    ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

RUN export http_proxy=http://oversea-squid4.sgp.txyun:11080 https_proxy=http://oversea-squid4.sgp.txyun:11080 && \
    apt-get update && \
    apt-get install openssh-client openssh-server openmpi-bin openmpi-doc libopenmpi-dev pdsh git-all iputils-ping lsof -y

RUN python3 -m pip install --upgrade pip && \
    pip3 install ninja && \
    MAX_JOBS=16 pip3 install flash-attn --no-build-isolation && \
    pip3 install deepspeed && \
    pip3 install qwen-vl-utils[decord] && \
    pip3 install rich pandas
    

RUN mkdir -p /root/.ssh && mkdir -p /var/run/sshd && rm -rf /etc/ssh/*
COPY --from=registry.corp.kuaishou.com/kml-platform/horovod-release:v3 /root/.ssh/ /root/.ssh/
COPY --from=registry.corp.kuaishou.com/kml-platform/horovod-release:v3 /etc/ssh/ssh_config /etc/ssh/
COPY --from=registry.corp.kuaishou.com/kml-platform/horovod-release:v3 /etc/ssh/sshd_config /etc/ssh/
COPY --from=registry.corp.kuaishou.com/kml-platform/horovod-release:v3 /etc/ssh/moduli /etc/ssh/
COPY --from=registry.corp.kuaishou.com/kml-platform/horovod-release:v3 /usr/local/etc/openmpi-mca-params.conf /usr/local/etc/
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key && ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key && ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key && ssh-keygen -A && chmod 700 /root/.ssh && chmod 600 /root/.ssh/authorized_keys && chmod 600 /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa.pub