dataset:
  type: ViTParquetDataset
  sources: /llm_reco_ssd/zangdunju/dataset/hdfs_data/vit/caption_v1.json
  num_epochs: 1
  num_workers: 4
  loader:
    num_workers: 4
    batch_size: 4
    collate_fn: VisionPackingCollator
  vision:
    resized_height: null
    resized_width: null
    multiple_of: 14
    min_pixels: 784
    max_pixels: 802816
    video_min_pixels: 25088
    video_max_pixels: 150528
    video_total_pixels: 4816896
    nframes: 10
    fps: null
    fps_min_frames: 4
    fps_max_frames: 32
  packing:
    enabled: true
    max_length: 8192
    drop_ratio: 0.0
    add_cls_token: false
  hooks:
    - type: TextLengthCheckHook
      position: before
    - type: VisionEncoderDataProcessorHook
      position: before
    - type: ImageProcessorHook
      position: after
  truncate_text_length: 64
model:
  siglip_dir: /llm_reco/liuyang76/Models/siglip2-so400m-patch14-384
  VitParam_dir: /llm_reco/liuyang76/Models/MoonVitParam/MoonVit.pt
  vision_return_embed_list: true
  interpolate_pos_encoding: true
  text_decoder:
    enabled: false
    loss_lambda: 2.0
    model_dir: /llm_reco/liuyang76/Models/Qwen2.5-0.5B-Instruct
optimizer:
  type: muon
  beta1: 0.9
  bata2: 0.95
  learn_rate: 1e-5
  weight_decay: 0.01
lr_scheduler:
  type: cosine
  num_warmup_steps: 18500
  num_training_steps: 370000
  min_lr: 0.0
monitor:
  type: ViTMonitor
strategy:
  type: ViTStrategy
  seed: 123456
  save_per_step: 1000
verbose:
  type: ViTVerbose
  verbose_per_step: 1
report:
  report_per_step: 1
gradient_checkpointing:
  enabled: true
