dataset:
  type: ViTParquetDataset
  sources: /llm_reco_ssd/zangdunju/dataset/hdfs_data/vit/test.json
  num_epochs: 2
  num_workers: 2
  loader:
    num_workers: 2
    batch_size: 4
    collate_fn: SingleImageTextPairCollator
model:
  siglip_dir: /llm_reco/liuyang76/Models/siglip2-so400m-patch14-384
  VitParam_dir: /llm_reco/liuyang76/Models/MoonVitParam/MoonVit.pt
  text_decoder:
    enabled: True
    model_dir: /llm_reco/liuyang76/Models/Qwen2.5-0.5B-Instruct
optimizer:
  type: muon
  beta1: 0.9
  bata2: 0.95
  learn_rate: 1e-3
  weight_decay: 0.01
lr_scheduler:
  type: cosine
  num_warmup_steps: 500
  num_training_steps: 10000
  min_lr: 0.0
monitor:
  type: ViTMonitor
strategy:
  type: ViTStrategy
  seed: 123456
  save_per_step: 100
verbose:
  type: ViTVerbose
  verbose_per_step: 1
report:
  report_per_step: 1
gradient_checkpointing:
  enabled: True
