dataset:
  type: ViTParquetDataset
  sources: /llm_reco_ssd/zangdunju/dataset/hdfs_data/vit/test.json
  num_epochs: 1
  num_workers: 2
  loader:
    num_workers: 2
    batch_size: 32
    collate_fn: SingleImageTextPairCollator
  packing:
    enabled: true
    max_length: 8192
    drop_ratio: 0.0
model:
  dir: /llm_reco_ssd/zhouyang12/models/SigLIP-So400M-Patch14-384/
  text_decoder:
    enabled: false
    model_dir: 234
optimizer:
  type: muon
  beta1: 0.9
  bata2: 0.95
  learn_rate: 1e-6
  weight_decay: 0.01
lr_scheduler:
  type: cosine
  num_warmup_steps: 200
  num_training_steps: 2000
  min_lr: 0.0
monitor:
  type: ViTMonitor
strategy:
  type: ViTStrategy
  seed: 123456
  save_per_step: 1000
verbose:
  type: ViTVerbose
  verbose_per_step: 1
report:
  report_per_step: 1

