
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/Keye/modular_Keye.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_Keye.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen Team and The HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from typing import List, Union

from transformers.feature_extraction_utils import BatchFeature
from transformers.image_utils import ImageInput, VideoInput
from transformers.processing_utils import ProcessingKwargs, ProcessorMixin, Unpack, VideosKwargs
from transformers.tokenization_utils_base import PreTokenizedInput, TextInput
from .image_processing_keye import SiglipImageProcessor
import torch
from itertools import chain

class KeyeVideosProcessorKwargs(VideosKwargs, total=False):
    fps: Union[List[float], float]


class KeyeProcessorKwargs(ProcessingKwargs, total=False):
    videos_kwargs: KeyeVideosProcessorKwargs
    _defaults = {
        "text_kwargs": {
            "padding": False,
        },
        "videos_kwargs": {"fps": 2.0},
    }


class KeyeProcessor(ProcessorMixin):
    r"""
    [`KeyeProcessor`] offers all the functionalities of [`SiglipImageProcessor`] and [`Qwen2TokenizerFast`]. See the
    [`~KeyeProcessor.__call__`] and [`~KeyeProcessor.decode`] for more information.
    Args:
        image_processor ([`SiglipImageProcessor`], *optional*):
            The image processor is a required input.
        tokenizer ([`Qwen2TokenizerFast`], *optional*):
            The tokenizer is a required input.
        chat_template (`str`, *optional*): A Jinja template which will be used to convert lists of messages
            in a chat into a tokenizable string.
    """

    attributes = ["image_processor", "tokenizer"]
    valid_kwargs = ["chat_template","image_std", "min_pixels", "image_mean", "merge_size", "image_processor_type", "temporal_patch_size", "patch_size", "max_pixels"]

    image_processor_class = "AutoImageProcessor"
    tokenizer_class = ("Qwen2Tokenizer", "Qwen2TokenizerFast")

    def __init__(self, image_processor=None, tokenizer=None, chat_template=None, **kwargs):
        self.image_token = "<|image_pad|>" if not hasattr(tokenizer, "image_token") else tokenizer.image_token
        self.video_token = "<|video_pad|>" if not hasattr(tokenizer, "video_token") else tokenizer.video_token
        self.frame_token = "<|frame|>" if not hasattr(tokenizer, "frame_token") else tokenizer.frame_token
        self.fast_video_token = "<|fast_video_pad|>" if not hasattr(tokenizer, "fast_video_token") else tokenizer.fast_video_token
        self.fast_start = "<|fast_start|>" if not hasattr(tokenizer, "fast_start") else tokenizer.fast_start
        self.fast_end = "<|fast_end|>" if not hasattr(tokenizer, "fast_end") else tokenizer.fast_end
        super().__init__(image_processor, tokenizer, chat_template=chat_template)

        # self.fast_patch_size = 16
        # self.fast_image_processor = SiglipImageProcessor(patch_size=self.fast_patch_size)
        self.slowfast = True

    def __call__(
        self,
        images: ImageInput = None,
        text: Union[TextInput, PreTokenizedInput, List[TextInput], List[PreTokenizedInput]] = None,
        videos: VideoInput = None,
        **kwargs: Unpack[KeyeProcessorKwargs],
    ) -> BatchFeature:
        """
        Main method to prepare for the model one or several sequences(s) and image(s). This method forwards the `text`
        and `kwargs` arguments to Qwen2TokenizerFast's [`~Qwen2TokenizerFast.__call__`] if `text` is not `None` to encode
        the text. To prepare the vision inputs, this method forwards the `vision_infos` and `kwrags` arguments to
        SiglipImageProcessor's [`~SiglipImageProcessor.__call__`] if `vision_infos` is not `None`.

        Args:
            images (`PIL.Image.Image`, `np.ndarray`, `torch.Tensor`, `List[PIL.Image.Image]`, `List[np.ndarray]`, `List[torch.Tensor]`):
                The image or batch of images to be prepared. Each image can be a PIL image, NumPy array or PyTorch
                tensor. Both channels-first and channels-last formats are supported.
            text (`str`, `List[str]`, `List[List[str]]`):
                The sequence or batch of sequences to be encoded. Each sequence can be a string or a list of strings
                (pretokenized string). If the sequences are provided as list of strings (pretokenized), you must set
                `is_split_into_words=True` (to lift the ambiguity with a batch of sequences).
            videos (`np.ndarray`, `torch.Tensor`, `List[np.ndarray]`, `List[torch.Tensor]`):
                The image or batch of videos to be prepared. Each video can be a 4D NumPy array or PyTorch
                tensor, or a nested list of 3D frames. Both channels-first and channels-last formats are supported.
            return_tensors (`str` or [`~utils.TensorType`], *optional*):
                If set, will return tensors of a particular framework. Acceptable values are:
                - `'tf'`: Return TensorFlow `tf.constant` objects.
                - `'pt'`: Return PyTorch `torch.Tensor` objects.
                - `'np'`: Return NumPy `np.ndarray` objects.
                - `'jax'`: Return JAX `jnp.ndarray` objects.

        Returns:
            [`BatchFeature`]: A [`BatchFeature`] with the following fields:

            - **input_ids** -- List of token ids to be fed to a model. Returned when `text` is not `None`.
            - **attention_mask** -- List of indices specifying which tokens should be attended to by the model (when
              `return_attention_mask=True` or if *"attention_mask"* is in `self.model_input_names` and if `text` is not
              `None`).
            - **pixel_values** -- Pixel values to be fed to a model. Returned when `images` is not `None`.
            - **pixel_values_videos** -- Pixel values of videos to be fed to a model. Returned when `videos` is not `None`.
            - **image_grid_thw** -- List of image 3D grid in LLM. Returned when `images` is not `None`.
            - **video_grid_thw** -- List of video 3D grid in LLM. Returned when `videos` is not `None`.
            - **second_per_grid_ts** -- List of video seconds per time grid. Returned when `videos` is not `None`.
        """
        output_kwargs = self._merge_kwargs(
            KeyeProcessorKwargs,
            tokenizer_init_kwargs=self.tokenizer.init_kwargs,
            **kwargs,
        )
        if images is not None:
            slow_images = images
            image_inputs = self.image_processor(images=slow_images, return_tensors="pt")
            image_inputs['pixel_values'] = image_inputs['pixel_values']
            image_grid_thw = image_inputs["image_grid_thw"]
        else:
            image_inputs = {}
            image_grid_thw = None


        if videos is not None:
            #TODO: add video processing
            all_slow_videos = []
            all_fast_videos = []
            # 这个是因为视频会划分为多张图片，需要在这个地方提前统计好token量，后面就不清楚界限在哪了
            slow_videos_token_nums = [[] for i in range(len(videos))]
            fast_videos_token_nums = [[] for i in range(len(videos))]
            all_position = []

            for current_index, current_video in enumerate(videos):
                if len(current_video) == 4: # slow_frames, fast_frames, time_position, slow_fast_order, 这里需要注意的是fast_frames，有可能和slow的长度不等，需要靠slow_fast_order来进行识别
                    slow_frames, fast_frames, time_position, slow_fast_order = current_video[0], current_video[1], current_video[2], current_video[3]
                    all_position.append((time_position, slow_fast_order))
                    ####### slow part #########
                    if slow_frames is not None:
                        slow_videos_inputs = self.image_processor(images=None, videos=slow_frames, **output_kwargs["images_kwargs"])
                        slow_video_grid_thw = slow_videos_inputs["video_grid_thw"]
                        all_slow_videos.append(slow_videos_inputs)
                        slow_videos_token_nums[current_index] = slow_video_grid_thw # .prod(dim=1).tolist() # 当前这个视频的所有token数
                    else:
                        all_slow_videos.append(None) # 这样的话，slow_fast_order都是1了，这里应该不会用到的
                        slow_videos_token_nums[current_index] = None # 如果全为fast？但目前不存在这种情况
                    ###########################

                    ####### fast part #########
                    if self.slowfast:
                        if fast_frames is not None:
                            fast_videos_inputs = self.image_processor(images=None, videos=fast_frames, **output_kwargs["images_kwargs"])
                            fast_video_grid_thw = fast_videos_inputs["video_grid_thw"]
                            all_fast_videos.append(fast_videos_inputs)
                            fast_videos_token_nums[current_index] = fast_video_grid_thw # .prod(dim=1).tolist() # 当前这个视频的fast的所有token数
                        else:
                            all_fast_videos.append(None) # 如果全为slow
                            fast_videos_token_nums[current_index] = None
                    ###########################
                else:
                    slow_frames, fast_frames, slow_fast_order = current_video[0], current_video[1], current_video[2]
                    if kwargs.get("image_video_pad", False):
                        fast_frames = slow_frames
                        slow_fast_order += [1]

                    all_position.append((None, slow_fast_order))
                    ####### slow part #########
                    if slow_frames is not None:
                        for each_image in slow_frames:
                            if kwargs.get("image_video_pad", False):
                                slow_videos_inputs = self.image_processor.preprocess(images=None, videos=[each_image], size = {"height": 28, "width": 28}, **output_kwargs["images_kwargs"])
                            else:
                                slow_videos_inputs = self.image_processor(images=None, videos=[each_image], **output_kwargs["images_kwargs"])
                            slow_video_grid_thw = slow_videos_inputs["video_grid_thw"]

                            all_slow_videos.append(slow_videos_inputs)
                            slow_videos_token_nums[current_index].append(slow_video_grid_thw) #.prod(dim=1).item()) # 这里因为没在前面split开，所以要这么写
                        ###########################
                    else:
                        all_slow_videos.append(None) # 这样的话，slow_fast_order都是1了，这里应该不会用到的
                        slow_videos_token_nums[current_index] = None # 如果全为fast？但目前不存在这种情况

                    ####### fast part #########
                    if self.slowfast:
                        if fast_frames is not None:
                            for each_image in fast_frames:
                                if kwargs.get("image_video_pad", False):
                                    fast_videos_inputs = self.image_processor.preprocess(images=None, videos=[each_image], size = {"height": 28, "width": 28}, **output_kwargs["images_kwargs"])
                                else:
                                    fast_videos_inputs = self.image_processor.preprocess(images=None, videos=[each_image], **output_kwargs["images_kwargs"])
                                fast_video_grid_thw = fast_videos_inputs["video_grid_thw"]

                                all_fast_videos.append(fast_videos_inputs)
                                fast_videos_token_nums[current_index].append(fast_video_grid_thw) # .prod(dim=1).item())
                        else:
                            all_fast_videos.append(None)
                            fast_videos_token_nums[current_index] = None
                    ###########################


            # todo: zdj debug 多次concat速度会慢很多
            slow_pixel_values_videos_list = [single_slow_video["pixel_values_videos"] for single_slow_video in all_slow_videos if single_slow_video is not None]
            slow_video_grid_thw_list = [single_slow_video["video_grid_thw"] for single_slow_video in all_slow_videos if single_slow_video is not None]

            total_slow_pixel_values_videos = torch.concat(slow_pixel_values_videos_list, dim=0)
            total_slow_video_grid_thw = torch.concat(slow_video_grid_thw_list, dim=0)
            # todo: zdj debug end

            if len(total_slow_pixel_values_videos):
                videos_inputs = {
                    "pixel_values_videos": total_slow_pixel_values_videos,
                    "video_grid_thw": total_slow_video_grid_thw,
                }
                video_grid_thw = videos_inputs["video_grid_thw"]
            else:
                videos_inputs = {}
                video_grid_thw = None

            if self.slowfast:
                # todo: zdj debug 多次concat速度会慢很多
                fast_pixel_values_videos_list = [single_fast_video["pixel_values_videos"] for single_fast_video in all_fast_videos if single_fast_video is not None]
                fast_video_grid_thw_list = [single_fast_video["video_grid_thw"] for single_fast_video in all_fast_videos if single_fast_video is not None]
                # fast_second_per_grid_ts = torch.tensor(list(chain(*fast_second_per_grid_ts_list)))

                if len(fast_pixel_values_videos_list):
                    videos_inputs["fast_pixel_values_videos"] = torch.concat(fast_pixel_values_videos_list, dim=0)
                    videos_inputs["fast_video_grid_thw"] = torch.concat(fast_video_grid_thw_list, dim=0)
                    fast_video_grid_thw = videos_inputs["fast_video_grid_thw"]
                else:
                    fast_video_grid_thw = None

                # todo: zdj debug end
        else:
            videos_inputs = {}
            video_grid_thw = None
            fast_video_grid_thw = None


        if not isinstance(text, list):
            text = [text]

        if image_grid_thw is not None:
            index = 0
            for i in range(len(text)):
                while self.image_token in text[i]:
                    # 4444 [<PIL.Image.Image image mode=RGB size=196x112 at 0x7F252BF9E980>] -> to_numpy -> (112, 196, 3)
                    # print(222222, image_inputs['pixel_values'].shape) # 222222 torch.Size([112, 3, 14, 14])
                    # print(111111, image_grid_thw, image_grid_thw[index].prod()//self.image_processor.merge_size//self.image_processor.merge_size) # 111111 tensor([[ 1,  8, 14]]) tensor(28)

                    _, h_merged, w_merged = image_grid_thw[index] // self.image_processor.merge_size
                    image_place_holder_tempale = ("<|placeholder|>" * w_merged + "<|mm_row_sep|>") * h_merged

                    # image_place_holder_tempale0 = "<|placeholder|>" * (image_grid_thw[index].prod()//self.image_processor.merge_size//self.image_processor.merge_size)
                    # print("image_place_holder_tempale0", image_place_holder_tempale0.count("<|placeholder|>"), image_place_holder_tempale.count("<|placeholder|>")); exit()
                    text[i] = text[i].replace(
                        self.image_token,
                        image_place_holder_tempale,
                        1,
                    )
                    index += 1
                text[i] = text[i].replace("<|placeholder|>", self.image_token)
            # text[0].count("<|placeholder|>")
        if video_grid_thw is not None or fast_video_grid_thw is not None:
            index = 0
            for i in range(len(text)):
                while self.video_token in text[i]:
                    video_place_holder_tempale = ""
                    slow_index = 0
                    fast_index = 0
                    # <|frame|>1.1<|placeholder|><|placeholder|> ... n_slow ... <|placeholder|><|fast_start|><|fast_placeholder|><|fast_placeholder|> ... n_fast ... <|fast_placeholder|><|fast_end|>
                    for j in range(len(all_position[index][1])):
                        if all_position[index][0] is not None: # 如果有时间戳
                            video_place_holder_tempale += self.frame_token + format(all_position[index][0][j], ".1f")
                        else:
                            video_place_holder_tempale += self.frame_token
                        if all_position[index][1][j] == 0: # 当前帧是slow？

                            # print(343433333, slow_video_grid_thw, slow_videos_token_nums); exit()
                            # print("slow_videos_token_nums[index][slow_index]slow_videos_token_nums[index][slow_index]", slow_videos_token_nums[index][slow_index])
                            _, h_merged, w_merged = slow_videos_token_nums[index][slow_index] // self.image_processor.merge_size
                            # video_place_holder_tempale += "<|placeholder|>" * (slow_videos_token_nums[index][slow_index]//self.image_processor.merge_size//self.image_processor.merge_size)
                            video_place_holder_tempale += ("<|placeholder|>" * w_merged + "<|mm_row_sep|>") * h_merged
                            # print("655776", slow_videos_token_nums[index][slow_index])
                            # print("fffeee", (("<|placeholder|>" * w_merged + "<|mm_row_sep|>") * h_merged).count("|placeholder|"), slow_videos_token_nums[index][slow_index].prod(0))
                            # print("3423232322", ("<|placeholder|>" * (slow_videos_token_nums[index][slow_index].prod(0)//self.image_processor.merge_size//self.image_processor.merge_size)).count("|placeholder|") )
                            slow_index += 1
                        elif all_position[index][1][j] == 1: # 当前帧是fast？
                            # video_place_holder_tempale += self.fast_start + "<|fast_placeholder|>" * (fast_videos_token_nums[index][fast_index]//self.image_processor.merge_size//self.image_processor.merge_size) + self.fast_end
                            _, h_merged, w_merged = fast_videos_token_nums[index][slow_index] // self.image_processor.merge_size
                            video_place_holder_tempale += self.fast_start +  ("<|fast_placeholder|>" * w_merged + "<|mm_row_sep|>") * h_merged
                            fast_index += 1
                    text[i] = text[i].replace(
                        self.video_token,
                        video_place_holder_tempale,
                        1,
                    )
                    index += 1
                #  self.tokenizer.decode(191678)
                # self.tokenizer.encode("<|fast_video_pad|>")
                text[i] = text[i].replace("<|placeholder|>", self.video_token)
                text[i] = text[i].replace("<|fast_placeholder|>", self.fast_video_token)
            # text[0].count(self.video_token)
        text_inputs = self.tokenizer(text, **output_kwargs["text_kwargs"])

        return BatchFeature(data={**text_inputs, **image_inputs, **videos_inputs})

    def batch_decode(self, *args, **kwargs):
        """
        This method forwards all its arguments to Qwen2TokenizerFast's [`~PreTrainedTokenizer.batch_decode`]. Please
        refer to the docstring of this method for more information.
        """
        return self.tokenizer.batch_decode(*args, **kwargs)

    def decode(self, *args, **kwargs):
        """
        This method forwards all its arguments to Qwen2TokenizerFast's [`~PreTrainedTokenizer.decode`]. Please refer to
        the docstring of this method for more information.
        """
        return self.tokenizer.decode(*args, **kwargs)

    def post_process_image_text_to_text(
        self, generated_outputs, skip_special_tokens=True, clean_up_tokenization_spaces=False, **kwargs
    ):
        """
        Post-process the output of the model to decode the text.

        Args:
            generated_outputs (`torch.Tensor` or `np.ndarray`):
                The output of the model `generate` function. The output is expected to be a tensor of shape `(batch_size, sequence_length)`
                or `(sequence_length,)`.
            skip_special_tokens (`bool`, *optional*, defaults to `True`):
                Whether or not to remove special tokens in the output. Argument passed to the tokenizer's `batch_decode` method.
            Clean_up_tokenization_spaces (`bool`, *optional*, defaults to `False`):
                Whether or not to clean up the tokenization spaces. Argument passed to the tokenizer's `batch_decode` method.
            **kwargs:
                Additional arguments to be passed to the tokenizer's `batch_decode method`.

        Returns:
            `List[str]`: The decoded text.
        """
        return self.tokenizer.batch_decode(
            generated_outputs,
            skip_special_tokens=skip_special_tokens,
            clean_up_tokenization_spaces=clean_up_tokenization_spaces,
            **kwargs,
        )

    @property
    def model_input_names(self):
        tokenizer_input_names = self.tokenizer.model_input_names
        image_processor_input_names = self.image_processor.model_input_names
        names_from_processor = list(dict.fromkeys(tokenizer_input_names + image_processor_input_names))
        return names_from_processor + ["second_per_grid_ts"]



__all__ = ["KeyeProcessor", "KeyeProcessor_moonvit", "KeyeProcessor"]



if __name__=='__main__':
    # /llm_reco/lingzhixin/recovlm_qw0510/recovlm/recovlm/models/keye_vitrope_slowfast_v4/processing_keye.py
    from recovlm.models.keye_vitrope_slowfast_v4.keye_vl_utils import process_vision_info
    from PIL import Image, ImageDraw
    from PIL import Image
    import torch
    import sys
    from transformers import AutoTokenizer, AutoModel, AutoProcessor
    import contextlib
    import os
    import shutil
    import json

    import subprocess
    import sys
    def generate_circle_image(size=(200, 200), fill_color=(0, 0, 0), outline_color=(255, 255, 255), outline_width=5):
        """
        生成一个包含一个圆的 PIL Image 对象。

        :param size: 图像的大小，默认为 (200, 200)
        :param fill_color: 圆的填充颜色，默认为黑色 (0, 0, 0)
        :param outline_color: 圆的轮廓颜色，默认为白色 (255, 255, 255)
        :param outline_width: 圆的轮廓宽度，默认为 5
        :return: 生成的 PIL Image 对象
        """
        # 创建一个新的图像对象
        image = Image.new('RGB', size, color=(255, 255, 255))
        draw = ImageDraw.Draw(image)
        # 计算圆的坐标（图像中心为圆心）
        x_center, y_center = size[0] // 2, size[1] // 2
        radius = min(size[0], size[1]) // 2
        # 绘制圆
        draw.ellipse([x_center - radius, y_center - radius, x_center + radius, y_center + radius],
                    fill=fill_color,
                    outline=outline_color,
                    width=outline_width)
        return image
    MODEL_DIR = "/mmu_mllm_hdd_2/zhouyang12/models/Keye-8B-demo_hf_vit_rope_slowfast_0714_sp1_sep"
    # /llm_reco/lingzhixin/recovlm_qw0510/recovlm/recovlm/models/keye_vitrope_slowfast_v4/processing_keye.py
    shutil.copy("/llm_reco/lingzhixin/recovlm_qw0510/recovlm/recovlm/models/keye_vitrope_slowfast_v4/processing_keye.py", MODEL_DIR)
    shutil.copy("/llm_reco/lingzhixin/recovlm_qw0510/recovlm/recovlm/models/keye_vitrope_slowfast_v4/image_processing_keye.py", MODEL_DIR)
    image = {"type": "image", "image": generate_circle_image((200,100),) , "max_pixels": 256*28*28}
    video = {"type": "video", "video": "/llm_reco/lingzhixin/recovlm_data/tests/2.mp4", "max_pixels": 256*28*28, "nframes": 4}
    messages = [
        {
            "role": "user",
            "content": [
                image,
                video,
                {"type": "text", "text": "what's in the image"},
            ],
        }
    ]
    processor = AutoProcessor.from_pretrained(MODEL_DIR, trust_remote_code=True)
    text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
    image_inputs, video_inputs = process_vision_info(messages)
    print(image_inputs) # <PIL.Image.Image image mode=RGB size=196x112 at 0x7F323E57E8F0>
    # 
    #
    inputs = processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    )
    print(inputs.keys())
    print(inputs["input_ids"]); exit()
    print(inputs)
    # PYTHONPATH=. python3 -m recovlm.models.keye_vitrope_slowfast_v4.processing_keye
