# 数据路径
data_path: /llm_reco/chuchenglong/R3/Ai_kwai/data/vqa_query_testdata_1500.json

# 输出目录
output_dir: /llm_reco/chuchenglong/R3/Ai_kwai/output_msy_0.3_pt

# 保存间隔（处理多少条数据后保存一次）
save_interval: 10

# 模型配置
model_dir: /llm_reco_ssd/luoxinchen/output3/RecoVLM-Base/0.3.0/cmt/global_step4001/merged_4001

vllm:
  # 推理所用的机器（台）
  num_inference_node: 8
  limit_mm_per_prompt: 10
  # tensor parallel size, 4 for Qwen2-VL-7B, 8 for 72B
  tp_size: 4

  # 采样参数
  temperature: 0.95
  top_p: 0.95
  repetition_penalty: 1.05
  max_tokens: 2048

