output_dir: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/zhangzixing/recovlm_dataset_grounding/AS10M_real_grounding
split_size: 268_435_456
dataset:
  class_name: ParquetDataset
  kwargs:
    path: viewfs://hadoop-lt-cluster/home/reco_wl/mpi/luoxinchen/recovlm_dataset_stage2/AS10M_real
converter:
  class_name: GroundingConverter
  kwargs:
    trans_type: box_trans
    pos_is_relative: true
    trans2segments: true